### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by IanaKhitsko** [maksganaychuk/Euro-Diffusion#5]
https://github.com/maksganaychuk/Euro-Diffusion/blob/4e458107a32d02ee946c9c3d4b43a5179fac2c5f/index.js#L56

Sorting first by days, then by name. It seems you have vice versa

**Comment by maksganaychuk** [comment]
no, it works correctly, if we want to have an array be sorted firstly by days, then we need to have this sorting to be the last in the code
